name: flame_playground
description: "Starting playing with Flame"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

#
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.30.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/Player.png
   - assets/images/Run.png
   - assets/images/Attack_1.png
   - assets/images/bg/1.png
   - assets/images/bg/2.png
   - assets/images/bg/3.png
   - assets/images/bg/4.png
   - assets/images/bg/5.png
   - assets/images/bg/6.png
   - assets/images/bg/7.png
   - assets/images/38.png
   - assets/images/explosion/Explosion_1.png
   - assets/images/explosion/Explosion_2.png
   - assets/images/explosion/Explosion_3.png
   - assets/images/explosion/Explosion_4.png
   - assets/images/explosion/Explosion_5.png
   - assets/images/explosion/Explosion_6.png
   - assets/images/explosion/Explosion_7.png
   - assets/images/explosion/Explosion_8.png
   - assets/images/explosion/Explosion_9.png
   - assets/images/explosion/Explosion_10.png
   
   


